# Generated by Django 6.0.6 on 2026-07-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_comment_id_alter_like_id_alter_post_id'),
        ('posts', '0002_alter_post_content'),
    ]

    operations = [
    ]
