# Generated by Django 5.2.15 on 2026-07-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_follow_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follow",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
